name: ner_influence
dependencies:
  - python=3.9
  - pytorch::pytorch=1.10.1
  - nvidia::cudatoolkit=11.3
  - pip
  - pandas
  - scipy
  - matplotlib
  - scikit-learn
  - conda-forge::faiss-cpu
  - pip:
    - transformers==4.12.5
    - pytorch-lightning==1.5.0
    - allennlp==2.8.0

  